# Generated by Django 5.2.7 on 2025-10-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_habit_created_at_completion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completion',
            unique_together=set(),
        ),
    ]
