# Generated by Django 5.2.7 on 2025-10-31 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_completion_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completion',
            name='date',
        ),
        migrations.AddField(
            model_name='completion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
